#!/bin/bash
set -e
set -o pipefail

# Check number of params
[ $# -ne 1 ] && echo "Usage: init project[.git]" && exit 1

# Set the project name, adding .git if necessary
p=$(echo "$1" | sed 's/\.git$\|$/.git/i')

[ -e "$p" ] && echo "$p is already a file or directory." && exit 1

git init --bare --initial-branch=main "$p"

echo "Glenn Lagasse" > "owner"
#echo "http://git.lan/${p%.git}" > "url"
echo "${p%.git}" > "description"
